"""Verify published PDFs and rebuild the Flutter inventory from sources.json.

Run after publishing Books/Prophets to main. --offline rebuilds metadata while
preserving previous successful verification for unchanged source hashes.
Uses Python's standard library only; no PDFs are bundled as Flutter assets.
"""
import argparse
import concurrent.futures
import hashlib
import json
from pathlib import Path
from urllib.parse import quote
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
STATUS = ROOT / 'tool/prophet_books_status.json'
OUTPUT = ROOT / 'lib/UI/prophets/prophet_book_inventory.dart'
BASE = 'https://raw.githubusercontent.com/bssam1996/Muslim/main/Books/Prophets/'
IDS = {'Al-Yasa': 'al_yasa', 'Dhul-Kifl': 'dhul_kifl', 'Saleh': 'salih',
       'Shuayyb': 'shuayb', 'Sulaiman': 'sulayman', 'Zakariyya': 'zakariya'}
SOURCE_KEYS = {'ibn-kathir-ar': 'Books_Source_Ibn_Kathir',
               'seoharwi-en': 'Books_Source_Seoharwi',
               'alsallabi-ibrahim-en': 'Books_Source_Ibrahim',
               'nectar-ar': 'Books_Source_Nectar', 'nectar-en': 'Books_Source_Nectar'}


def dart_string(value):
    return json.dumps(value, ensure_ascii=False).replace('$', r'\$')


def verify(book):
    try:
        with urlopen(BASE + quote(book['file'], safe='/'), timeout=90) as response:
            content = response.read()
        assert len(content) == book['bytes'], 'Size mismatch'
        assert content.startswith(b'%PDF-') and b'%%EOF' in content[-1024:], 'Incomplete PDF'
        assert hashlib.sha256(content).hexdigest() == book['sha256'], 'SHA-256 mismatch'
        # Matching the reviewed local PDF's complete hash also verifies that the
        # remote bytes are the exact readable edition reviewed locally.
        return book['file'], book['sha256'], None
    except Exception as error:
        return book['file'], None, str(error)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--offline', action='store_true')
    args = parser.parse_args()
    inventory = json.loads((ROOT / 'Books/Prophets/sources.json').read_text(encoding='utf-8'))
    verified = json.loads(STATUS.read_text()) if STATUS.exists() else {}
    if not args.offline:
        with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
            results = list(pool.map(verify, inventory['books']))
        verified = {file: digest for file, digest, error in results if digest is not None}
        for file, digest, error in results:
            if error:
                print(f'Unavailable: {file}: {error}')
    verified = {book['file']: book['sha256'] for book in inventory['books']
                if verified.get(book['file']) == book['sha256']}
    lines = ["// Generated by tool/verify_prophet_books.py; edit sources.json instead.",
             "import '../books/library_book.dart';", '',
             'const prophetBookInventory = <LibraryBook>[']
    for book in inventory['books']:
        file = ROOT / 'Books/Prophets' / book['file']
        content = file.read_bytes()
        assert len(content) == book['bytes']
        assert hashlib.sha256(content).hexdigest() == book['sha256'], book['file']
        prophet_id = IDS.get(book['prophet'], book['prophet'].lower())
        title = 'Prophets_Kids_Story' if book['edition'] == 'kids' else 'Prophets_Full_Story'
        details = book['provenance']
        lines.extend(['  LibraryBook(',
                      f"    id: {dart_string('prophet_' + prophet_id + '_' + book['edition'] + '_' + book['language'])},",
                      f'    titleKey: {dart_string(title)},',
                      f"    language: {dart_string(book['language'])},",
                      f"    approximateBytes: {book['bytes']},",
                      f"    downloadUrl: {dart_string(BASE + quote(book['file'], safe='/'))},",
                      f"    available: {'true' if book['file'] in verified else 'false'},"])
        source_id = details.get('source_id')
        if source_id:
            key = SOURCE_KEYS.get(source_id)
            if key:
                lines.append(f'    sourceKey: {dart_string(key)},')
            else:
                source = inventory['adult_source_books'][source_id]['author']
                lines.append(f'    source: {dart_string(source)},')
            note = 'Books_Adult_Edition_Note'
        elif book['language'] == 'ar':
            lines.append('    sourceKey: "Books_Original_Arabic_Story",')
            note = None
        else:
            source = details.get('author_source')
            if source:
                lines.append(f'    source: {dart_string(source)},')
            note = 'Books_Unofficial_Translation' if 'unofficial' in details.get('kind', '') else None
        if note:
            lines.append(f'    noteKey: {dart_string(note)},')
        lines.append('  ),')
    lines.extend(['];', ''])
    OUTPUT.write_text('\n'.join(lines), encoding='utf-8')
    STATUS.write_text(json.dumps(verified, indent=2) + '\n', encoding='utf-8')
    print(f'Generated {len(inventory["books"])} editions; {len(verified)} published PDFs verified.')


if __name__ == '__main__':
    main()
