import 'package:muslim/UI/radio/radio_station.dart';

const List<RadioStation> radioStations = <RadioStation>[
  RadioStation(
    id: 1,
    englishName: "Radio Ibrahim Al-Akdar",
    arabicName: "إذاعة إبراهيم الأخضر",
    url: "https://backup.qurango.net/radio/ibrahim_alakdar",
  ),
  RadioStation(
    id: 2,
    englishName: "Radio Shaik Abu Bakr Al Shatri",
    arabicName: "إذاعة شيخ أبو بكر الشاطري",
    url: "https://backup.qurango.net/radio/shaik_abu_bakr_al_shatri",
  ),
  RadioStation(
    id: 3,
    englishName: "Radio Ahmad Al-Ajmy",
    arabicName: "إذاعة أحمد العجمي",
    url: "https://backup.qurango.net/radio/ahmad_alajmy",
  ),
  RadioStation(
    id: 4,
    englishName: "Radio Ahmad Al-Hawashi",
    arabicName: "إذاعة أحمد الحواشي",
    url: "https://backup.qurango.net/radio/ahmad_alhawashi",
  ),
  RadioStation(
    id: 5,
    englishName: "Radio Ahmad Saber",
    arabicName: "إذاعة أحمد صابر",
    url: "https://backup.qurango.net/radio/ahmad_saber",
  ),
  RadioStation(
    id: 6,
    englishName: "Radio Ahmad Nauina",
    arabicName: "إذاعة أحمد نعينع",
    url: "https://backup.qurango.net/radio/ahmad_nauina",
  ),
  RadioStation(
    id: 7,
    englishName: "Radio Akram Alalaqmi",
    arabicName: "إذاعة أكرم العلاقمي",
    url: "https://backup.qurango.net/radio/akram_alalaqmi",
  ),
  RadioStation(
    id: 8,
    englishName: "Radio Idrees Abkr",
    arabicName: "إذاعة إدريس أبكر",
    url: "https://backup.qurango.net/radio/idrees_abkr",
  ),
  RadioStation(
    id: 9,
    englishName: "Radio Alzain Mohammad Ahmad",
    arabicName: "إذاعة الزين محمد أحمد",
    url: "https://backup.qurango.net/radio/alzain_mohammad_ahmad",
  ),
  RadioStation(
    id: 10,
    englishName: "Radio Al-Qaria Yassen",
    arabicName: "إذاعة القارئ ياسين",
    url: "https://backup.qurango.net/radio/alqaria_yassen",
  ),
  RadioStation(
    id: 11,
    englishName: "Radio Aloyoon Al-Koshi",
    arabicName: "إذاعة العيون الكوشي",
    url: "https://backup.qurango.net/radio/aloyoon_alkoshi",
  ),
  RadioStation(
    id: 12,
    englishName: "Radio Tawfeeq As-Sayegh",
    arabicName: "إذاعة توفيق الصايغ",
    url: "https://backup.qurango.net/radio/tawfeeq_assayegh",
  ),
  RadioStation(
    id: 13,
    englishName: "Radio Jamal Shaker Abdullah",
    arabicName: "إذاعة جمال شاكر عبدالله",
    url: "https://backup.qurango.net/radio/jamal_shaker_abdullah",
  ),
  RadioStation(
    id: 14,
    englishName: "Radio Khaled Al-Qahtani",
    arabicName: "إذاعة خالد القحطاني",
    url: "https://backup.qurango.net/radio/khaled_alqahtani",
  ),
  RadioStation(
    id: 15,
    englishName: "Radio Khalid Abdulkafi",
    arabicName: "إذاعة خالد عبدالكافي",
    url: "https://backup.qurango.net/radio/khalid_abdulkafi",
  ),
  RadioStation(
    id: 16,
    englishName: "Radio Khalifa Altunaiji",
    arabicName: "إذاعة خليفة الطنيجي",
    url: "https://backup.qurango.net/radio/khalifa_altunaiji",
  ),
  RadioStation(
    id: 17,
    englishName: "Radio Saad Al-Ghamdi",
    arabicName: "إذاعة سعد الغامدي",
    url: "https://backup.qurango.net/radio/saad_alghamdi",
  ),
  RadioStation(
    id: 18,
    englishName: "Radio Saud Al-Shuraim",
    arabicName: "إذاعة سعود الشريم",
    url: "https://backup.qurango.net/radio/saud_alshuraim",
  ),
  RadioStation(
    id: 19,
    englishName: "Radio Sahl Yassin",
    arabicName: "إذاعة سهل ياسين",
    url: "https://backup.qurango.net/radio/sahl_yassin",
  ),
  RadioStation(
    id: 20,
    englishName: "Radio Zaki Daghistani",
    arabicName: "إذاعة زكي داغستاني",
    url: "https://backup.qurango.net/radio/zaki_daghistani",
  ),
  RadioStation(
    id: 21,
    englishName: "Radio Sayeed Ramadan",
    arabicName: "إذاعة سيد رمضان",
    url: "https://backup.qurango.net/radio/sayeed_ramadan",
  ),
  RadioStation(
    id: 22,
    englishName: "Radio Shirazad Taher",
    arabicName: "إذاعة شيرزاد عبدالرحمن طاهر",
    url: "https://backup.qurango.net/radio/shirazad_taher",
  ),
  RadioStation(
    id: 23,
    englishName: "Radio Saber Abdulhakm",
    arabicName: "إذاعة صابر عبدالحكم",
    url: "https://backup.qurango.net/radio/saber_abdulhakm",
  ),
  RadioStation(
    id: 24,
    englishName: "Radio Salah Albudair",
    arabicName: "إذاعة صلاح البدير",
    url: "https://backup.qurango.net/radio/salah_albudair",
  ),
  RadioStation(
    id: 25,
    englishName: "Radio Salah Alhashim",
    arabicName: "إذاعة صلاح الهاشم",
    url: "https://backup.qurango.net/radio/salah_alhashim",
  ),
  RadioStation(
    id: 26,
    englishName: "Radio Slaah Bukhatir",
    arabicName: "إذاعة صلاح بو خاطر",
    url: "https://backup.qurango.net/radio/slaah_bukhatir",
  ),
  RadioStation(
    id: 27,
    englishName: "Radio Adel Ryyan",
    arabicName: "إذاعة عادل ريان",
    url: "https://backup.qurango.net/radio/adel_ryyan",
  ),
  RadioStation(
    id: 28,
    englishName: "Radio Abdelbari Al-Thoubayti",
    arabicName: "إذاعة عبدالبارئ الثبيتي",
    url: "https://backup.qurango.net/radio/abdelbari_altoubayti",
  ),
  RadioStation(
    id: 29,
    englishName: "Radio Abdulbari Mohammad",
    arabicName: "إذاعة عبدالبارئ محمد",
    url: "https://backup.qurango.net/radio/abdulbari_mohammad",
  ),
  RadioStation(
    id: 30,
    englishName: "Radio Abdulbasit Abdulsamad mojawwad",
    arabicName: "إذاعة عبدالباسط عبدالصمد مجوّد",
    url: "https://backup.qurango.net/radio/abdulbasit_abdulsamad_mojawwad",
  ),
  RadioStation(
    id: 31,
    englishName: "Radio Abdulbasit Abdulsamad warsh",
    arabicName: "إذاعة عبدالباسط عبدالصمد ورش",
    url: "https://backup.qurango.net/radio/abdulbasit_abdulsamad_warsh",
  ),
  RadioStation(
    id: 32,
    englishName: "Radio Abdulbasit Abdulsamad",
    arabicName: "إذاعة عبدالباسط عبدالصمد",
    url: "https://backup.qurango.net/radio/abdulbasit_abdulsamad",
  ),
  RadioStation(
    id: 33,
    englishName: "Radio Abdulrahman Alsudaes",
    arabicName: "إذاعة عبدالرحمن السديس",
    url: "https://backup.qurango.net/radio/abdulrahman_alsudaes",
  ),
  RadioStation(
    id: 34,
    englishName: "Radio Abdul Aziz Al-Ahmad",
    arabicName: "إذاعة عبدالعزيز الأحمد",
    url: "https://backup.qurango.net/radio/abdul_aziz_alahmad",
  ),
  RadioStation(
    id: 35,
    englishName: "Radio Abdullah Al-Mattrod",
    arabicName: "إذاعة عبدالله المطرود",
    url: "https://backup.qurango.net/radio/abdullah_almattrod",
  ),
  RadioStation(
    id: 36,
    englishName: "Radio Abdullah Basfer",
    arabicName: "إذاعة عبدالله بصفر",
    url: "https://backup.qurango.net/radio/abdullah_basfer",
  ),
  RadioStation(
    id: 37,
    englishName: "Radio Abdullah Khayyat",
    arabicName: "إذاعة عبدالله خياط",
    url: "https://backup.qurango.net/radio/abdullah_khayyat",
  ),
  RadioStation(
    id: 38,
    englishName: "Radio Abdullah Al-Johany",
    arabicName: "إذاعة عبدالله عواد الجهني",
    url: "https://backup.qurango.net/radio/abdullah_aljohany",
  ),
  RadioStation(
    id: 39,
    englishName: "Radio Abdulrasheed Soufi",
    arabicName: "إذاعة عبدالرشيد صوفي",
    url: "https://backup.qurango.net/radio/abdulrasheed_soufi_khalaf",
  ),
  RadioStation(
    id: 40,
    englishName: "Radio Abdulrasheed Soufi",
    arabicName: "إذاعة عبدالرشيد صوفي",
    url: "https://backup.qurango.net/radio/abdulrasheed_soufi_assosi",
  ),
  RadioStation(
    id: 41,
    englishName: "Radio Abdulmohsin Al-Harthy",
    arabicName: "إذاعة عبدالمحسن الحارثي",
    url: "https://backup.qurango.net/radio/abdulmohsin_alharthy",
  ),
  RadioStation(
    id: 42,
    englishName: "Radio Abdulmohsen Al-Qasim",
    arabicName: "إذاعة عبدالمحسن القاسم",
    url: "https://backup.qurango.net/radio/abdulmohsen_alqasim",
  ),
  RadioStation(
    id: 43,
    englishName: "Radio Abdulmohsin Al-Obaikan",
    arabicName: "إذاعة عبدالمحسن العبيكان",
    url: "https://backup.qurango.net/radio/abdulmohsin_alobaikan",
  ),
  RadioStation(
    id: 44,
    englishName: "Radio Abdulhadi Kanakeri",
    arabicName: "إذاعة عبدالهادي أحمد كناكري",
    url: "https://backup.qurango.net/radio/abdulhadi_kanakeri",
  ),
  RadioStation(
    id: 45,
    englishName: "Radio Abdulwadood Haneef",
    arabicName: "إذاعة عبدالودود حنيف",
    url: "https://backup.qurango.net/radio/abdulwadood_haneef",
  ),
  RadioStation(
    id: 46,
    englishName: "Radio Ali Alhuthaifi",
    arabicName: "إذاعة علي بن عبدالرحمن الحذيفي",
    url: "https://backup.qurango.net/radio/ali_alhuthaifi",
  ),
  RadioStation(
    id: 47,
    englishName: "Radio Ali Alhuthaifi",
    arabicName: "إذاعة علي الحذيفي",
    url: "https://backup.qurango.net/radio/ali_alhuthaifi_qalon",
  ),
  RadioStation(
    id: 48,
    englishName: "Radio Ali Jaber",
    arabicName: "إذاعة علي جابر",
    url: "https://backup.qurango.net/radio/ali_jaber",
  ),
  RadioStation(
    id: 49,
    englishName: "Radio Ali Hajjaj Alsouasi",
    arabicName: "إذاعة علي حجاج السويسي",
    url: "https://backup.qurango.net/radio/ali_hajjaj_alsouasi",
  ),
  RadioStation(
    id: 50,
    englishName: "Radio Emad Hafez",
    arabicName: "إذاعة عماد زهير حافظ",
    url: "https://backup.qurango.net/radio/emad_hafez",
  ),
  RadioStation(
    id: 51,
    englishName: "Radio Omar Al-Qazabri",
    arabicName: "إذاعة عمر القزابري",
    url: "https://backup.qurango.net/radio/omar_alqazabri",
  ),
  RadioStation(
    id: 52,
    englishName: "Radio Fares Abbad",
    arabicName: "إذاعة فارس عباد",
    url: "https://backup.qurango.net/radio/fares_abbad",
  ),
  RadioStation(
    id: 53,
    englishName: "Radio Nasser Alqatami",
    arabicName: "إذاعة ناصر القطامي",
    url: "https://backup.qurango.net/radio/nasser_alqatami",
  ),
  RadioStation(
    id: 54,
    englishName: "Radio Nabil Al Rifay",
    arabicName: "إذاعة نبيل الرفاعي",
    url: "https://backup.qurango.net/radio/nabil_al_rifay",
  ),
  RadioStation(
    id: 55,
    englishName: "Radio Neamah Al-Hassan",
    arabicName: "إذاعة نعمة الحسان",
    url: "https://backup.qurango.net/radio/neamah_alhassan",
  ),
  RadioStation(
    id: 56,
    englishName: "Radio Hani Arrifai",
    arabicName: "إذاعة هاني الرفاعي",
    url: "https://backup.qurango.net/radio/hani_arrifai",
  ),
  RadioStation(
    id: 57,
    englishName: "Radio Waleed Alnaehi",
    arabicName: "إذاعة وليد النائحي",
    url: "https://backup.qurango.net/radio/waleed_alnaehi",
  ),
  RadioStation(
    id: 58,
    englishName: "Radio Yasser Al-Dosari",
    arabicName: "إذاعة ياسر الدوسري",
    url: "https://backup.qurango.net/radio/yasser_aldosari",
  ),
  RadioStation(
    id: 59,
    englishName: "Radio Yasser Al-Qurashi",
    arabicName: "إذاعة ياسر القرشي",
    url: "https://backup.qurango.net/radio/yasser_alqurashi",
  ),
  RadioStation(
    id: 60,
    englishName: "Radio Yasser Al-Mazroyee",
    arabicName: "إذاعة ياسر المزروعي",
    url: "https://backup.qurango.net/radio/yasser_almazroyee",
  ),
  RadioStation(
    id: 61,
    englishName: "Radio Yahya Hawwa",
    arabicName: "إذاعة يحيى حوا",
    url: "https://backup.qurango.net/radio/yahya_hawwa",
  ),
  RadioStation(
    id: 62,
    englishName: "Radio Yousef Alshoaey",
    arabicName: "إذاعة يوسف الشويعي",
    url: "https://backup.qurango.net/radio/yousef_alshoaey",
  ),
  RadioStation(
    id: 63,
    englishName: "Radio Maher Al Meaqli",
    arabicName: "إذاعة ماهر المعيقلي",
    url: "https://backup.qurango.net/radio/maher",
  ),
  RadioStation(
    id: 64,
    englishName: "Radio Mohammad Al-Tablaway",
    arabicName: "إذاعة محمد الطبلاوي",
    url: "https://backup.qurango.net/radio/mohammad_altablaway",
  ),
  RadioStation(
    id: 65,
    englishName: "Radio Mohammed Al-Lohaidan",
    arabicName: "إذاعة محمد اللحيدان",
    url: "https://backup.qurango.net/radio/mohammed_allohaidan",
  ),
  RadioStation(
    id: 66,
    englishName: "Radio Mohammed Ayyub",
    arabicName: "إذاعة محمد أيوب",
    url: "https://backup.qurango.net/radio/mohammed_ayyub",
  ),
  RadioStation(
    id: 67,
    englishName: "Radio Mohammad Saleh Alim Shah",
    arabicName: "إذاعة محمد صالح عالم شاه",
    url: "https://backup.qurango.net/radio/mohammad_saleh_alim_shah",
  ),
  RadioStation(
    id: 68,
    englishName: "Radio Mohammed Jibreel",
    arabicName: "إذاعة محمد جبريل",
    url: "https://backup.qurango.net/radio/mohammed_jibreel",
  ),
  RadioStation(
    id: 69,
    englishName: "Radio Mohammed Siddiq Al-Minshawi",
    arabicName: "إذاعة محمد صديق المنشاوي",
    url: "https://backup.qurango.net/radio/mohammed_siddiq_alminshawi",
  ),
  RadioStation(
    id: 70,
    englishName: "Radio Mohammed Siddiq Al-Minshawi",
    arabicName: "إذاعة محمد صديق المنشاوي",
    url: "https://backup.qurango.net/radio/mohammed_siddiq_alminshawi_mojawwad",
  ),
  RadioStation(
    id: 71,
    englishName: "Radio Mohammad Abdullkarem",
    arabicName: "إذاعة محمد عبدالكريم",
    url: "https://backup.qurango.net/radio/mohammad_abdullkarem",
  ),
  RadioStation(
    id: 72,
    englishName: "Radio Mohammad Al-Abdullah",
    arabicName: "إذاعة محمد عبدالحكيم سعيد العبدالله",
    url: "https://backup.qurango.net/radio/mohammad_alabdullah_albizi",
  ),
  RadioStation(
    id: 73,
    englishName: "Radio Mohammad Al-Abdullah",
    arabicName: "إذاعة محمد عبدالحكيم سعيد العبدالله",
    url: "https://backup.qurango.net/radio/mohammad_alabdullah_aldorai",
  ),
  RadioStation(
    id: 74,
    englishName: "Radio Mahmoud Khalil Al-Hussary",
    arabicName: "إذاعة محمود خليل الحصري",
    url: "https://backup.qurango.net/radio/mahmoud_khalil_alhussary",
  ),
  RadioStation(
    id: 75,
    englishName: "Radio Mahmoud Khalil Al-Hussary",
    arabicName: "إذاعة محمود خليل الحصري",
    url: "https://backup.qurango.net/radio/mahmoud_khalil_alhussary_mojawwad",
  ),
  RadioStation(
    id: 76,
    englishName: "Radio Mahmoud Khalil Al-Hussary",
    arabicName: "إذاعة محمود خليل الحصري",
    url: "https://backup.qurango.net/radio/mahmoud_khalil_alhussary_warsh",
  ),
  RadioStation(
    id: 77,
    englishName: "Radio Mahmoud Ali  Albanna",
    arabicName: "إذاعة محمود علي البنا",
    url: "https://backup.qurango.net/radio/mahmoud_ali__albanna",
  ),
  RadioStation(
    id: 78,
    englishName: "Radio Mahmoud Ali  Albanna",
    arabicName: "إذاعة محمود علي البنا",
    url: "https://backup.qurango.net/radio/mahmoud_ali__albanna_mojawwad",
  ),
  RadioStation(
    id: 79,
    englishName: "Radio Mishary Alafasi",
    arabicName: "إذاعة مشاري العفاسي",
    url: "https://backup.qurango.net/radio/mishary_alafasi",
  ),
  RadioStation(
    id: 80,
    englishName: "Radio Mustafa Ismail",
    arabicName: "إذاعة مصطفى إسماعيل",
    url: "https://backup.qurango.net/radio/mustafa_ismail",
  ),
  RadioStation(
    id: 81,
    englishName: "Radio Mustafa Al-Lahoni",
    arabicName: "إذاعة مصطفى اللاهوني",
    url: "https://backup.qurango.net/radio/mustafa_allahoni",
  ),
  RadioStation(
    id: 82,
    englishName: "Radio Mustafa raad Alazawy",
    arabicName: "إذاعة مصطفى رعد العزاوي",
    url: "https://backup.qurango.net/radio/mustafa_raad_alazawy",
  ),
  RadioStation(
    id: 83,
    englishName: "Radio Muftah Alsaltany",
    arabicName: "إذاعة مفتاح السلطني",
    url: "https://backup.qurango.net/radio/muftah_alsaltany_aldori_an_abi_amr",
  ),
  RadioStation(
    id: 84,
    englishName: "Radio Maher Shakhashero",
    arabicName: "إذاعة ماهر شخاشيرو",
    url: "https://backup.qurango.net/radio/maher_shakhashero",
  ),
  RadioStation(
    id: 85,
    englishName: "Radio Mahmood AlSheimy",
    arabicName: "إذاعة محمود الشيمي",
    url: "https://backup.qurango.net/radio/mahmood_alsheimy",
  ),
  RadioStation(
    id: 86,
    englishName: "Radio Khalid Almohana",
    arabicName: "إذاعة خالد المهنا",
    url: "https://backup.qurango.net/radio/khalid_almohana",
  ),
  RadioStation(
    id: 87,
    englishName: "Radio Adel Al-Khalbany",
    arabicName: "إذاعة عادل الكلباني",
    url: "https://backup.qurango.net/radio/adel_alkhalbany",
  ),
  RadioStation(
    id: 88,
    englishName: "Radio Mousa Bilal",
    arabicName: "إذاعة موسى بلال",
    url: "https://backup.qurango.net/radio/mousa_bilal",
  ),
  RadioStation(
    id: 89,
    englishName: "Radio Hatem Fareed Alwaer",
    arabicName: "حاتم فريد الواعر",
    url: "https://backup.qurango.net/radio/hatem_fareed_alwaer",
  ),
  RadioStation(
    id: 90,
    englishName: "Radio Mahmood Al rifai",
    arabicName: "إذاعة محمود الرفاعي",
    url: "https://backup.qurango.net/radio/mahmood_al_rifai",
  ),
  RadioStation(
    id: 91,
    englishName: "Radio Ibrahim Aldosari",
    arabicName: "إذاعة ابراهيم الدوسري",
    url: "https://backup.qurango.net/radio/ibrahim_aldosari",
  ),
  RadioStation(
    id: 92,
    englishName: "Radio Muftah Alsaltany",
    arabicName: "إذاعة مفتاح السلطني",
    url: "https://backup.qurango.net/radio/muftah_alsaltany_aldorai",
  ),
  RadioStation(
    id: 93,
    englishName: "Radio Jamaan Alosaimi",
    arabicName: "إذاعة جمعان العصيمي",
    url: "https://backup.qurango.net/radio/jamaan_alosaimi",
  ),
  RadioStation(
    id: 94,
    englishName: "Radio Muftah Alsaltany",
    arabicName: "إذاعة مفتاح السلطني",
    url: "https://backup.qurango.net/radio/muftah_alsaltany",
  ),
  RadioStation(
    id: 95,
    englishName: "Radio Yousef Bin Noah Ahmad",
    arabicName: "إذاعة يوسف بن نوح أحمد",
    url: "https://backup.qurango.net/radio/yousef_bin_noah_ahmad",
  ),
  RadioStation(
    id: 96,
    englishName: "Radio Muftah Alsaltany",
    arabicName: "إذاعة مفتاح السلطني",
    url:
        "https://backup.qurango.net/radio/muftah_alsaltany_ibn_thakwan_an_ibn_amr",
  ),
  RadioStation(
    id: 97,
    englishName: "Radio Moeedh Alharthi",
    arabicName: "إذاعة معيض الحارثي",
    url: "https://backup.qurango.net/radio/moeedh_alharthi",
  ),
  RadioStation(
    id: 98,
    englishName: "Radio Mohammad Rashad Alshareef",
    arabicName: "إذاعة محمد رشاد الشريف",
    url: "https://backup.qurango.net/radio/mohammad_rashad_alshareef",
  ),
  RadioStation(
    id: 99,
    englishName: "Radio Ahmad Khader Al-Tarabulsi",
    arabicName: "إذاعة أحمد خضر الطرابلسي",
    url: "https://backup.qurango.net/radio/ahmad_khader_altarabulsi",
  ),
  RadioStation(
    id: 100,
    englishName: "Radio Ahmed Al-trabulsi",
    arabicName: "إذاعة أحمد الطرابلسي",
    url: "https://backup.qurango.net/radio/ahmed_altrabulsi",
  ),
  RadioStation(
    id: 101,
    englishName: "Radio Abdullah Al-Kandari",
    arabicName: "إذاعة عبدالله الكندري",
    url: "https://backup.qurango.net/radio/abdullah_alkandari",
  ),
  RadioStation(
    id: 102,
    englishName: "Radio Ahmed Amer",
    arabicName: "إذاعة أحمد عامر",
    url: "https://backup.qurango.net/radio/ahmed_amer",
  ),
  RadioStation(
    id: 103,
    englishName: "Radio Mohammed Osman Khan",
    arabicName: "إذاعة محمد عثمان خان",
    url: "https://backup.qurango.net/radio/mohammed_osman_khan",
  ),
  RadioStation(
    id: 104,
    englishName: "Radio Addokali Mohammad Alalim",
    arabicName: "إذاعة الدوكالي محمد العالم",
    url: "https://backup.qurango.net/radio/addokali_mohammad_alalim",
  ),
  RadioStation(
    id: 105,
    englishName: "Radio Mohammad Abdullkarem",
    arabicName: "إذاعة محمد عبدالكريم",
    url: "https://backup.qurango.net/radio/mohammad_abdullkarem_alasbahani",
  ),
  RadioStation(
    id: 106,
    englishName: "Radio Alfateh Alzubair",
    arabicName: "إذاعة الفاتح محمد الزبير",
    url: "https://backup.qurango.net/radio/alfateh_alzubair",
  ),
  RadioStation(
    id: 107,
    englishName: "Radio Tareq Abdulgani daawob",
    arabicName: "إذاعة طارق عبدالغني دعوب",
    url: "https://backup.qurango.net/radio/tareq_abdulgani_daawob",
  ),
  RadioStation(
    id: 108,
    englishName: "-Main Radio-",
    arabicName: "-الإذاعة العامة - اذاعة متنوعة لمختلف القراء",
    url: "https://backup.qurango.net/radio/mix",
  ),
  RadioStation(
    id: 109,
    englishName: "-Beautiful Recitations-",
    arabicName: "إذاعة -تلاوات خاشعة-",
    url: "https://backup.qurango.net/radio/salma",
  ),
  RadioStation(
    id: 110,
    englishName: "Eid Takbeer",
    arabicName: "إذاعة تكبيرات العيد",
    url: "https://backup.qurango.net/radio/eid",
  ),
  RadioStation(
    id: 111,
    englishName: "Radio Abdulrahman Al-Majed",
    arabicName: "إذاعة عبدالرحمن الماجد",
    url: "https://backup.qurango.net/radio/abdulrahman_almajed",
  ),
  RadioStation(
    id: 112,
    englishName: "General Fatwa Radio",
    arabicName: "إذاعة الفتاوى العامة",
    url: "https://backup.qurango.net/radio/fatwa",
  ),
  RadioStation(
    id: 113,
    englishName: "Sharia ruqyah",
    arabicName: "إذاعة الرقية الشرعية",
    url: "https://backup.qurango.net/radio/roqiah",
  ),
  RadioStation(
    id: 114,
    englishName: "-Surah Al-Baqarah - Many Reciters-",
    arabicName: "إذاعة ---سورة البقرة - لعدد من القراء---",
    url: "https://backup.qurango.net/radio/albaqarah",
  ),
  RadioStation(
    id: 115,
    englishName: "--Quran Tafseer--",
    arabicName: "إذاعة --تفسير القران الكريم--",
    url: "https://backup.qurango.net/radio/tafseer",
  ),
  RadioStation(
    id: 116,
    englishName: "Khalid Al-Jileel",
    arabicName: "إذاعة خالد الجليل",
    url: "https://backup.qurango.net/radio/khalid_aljileel",
  ),
  RadioStation(
    id: 117,
    englishName: "Nasser Almajed",
    arabicName: "إذاعة ناصر الماجد",
    url: "https://backup.qurango.net/radio/nasser_almajed",
  ),
  RadioStation(
    id: 118,
    englishName: "Haitham Aljudaany",
    arabicName: "إذاعة هيثم الجدعاني",
    url: "https://backup.qurango.net/radio/hitham_aljadani",
  ),
  RadioStation(
    id: 119,
    englishName: "Ahmad Shaheen",
    arabicName: "إذاعة أحمد خليل شاهين",
    url: "https://backup.qurango.net/radio/ahmad_shaheen",
  ),
  RadioStation(
    id: 120,
    englishName: "Abdullah Al-Mousa - Radio",
    arabicName: "إذاعة عبدالله الموسى",
    url: "https://backup.qurango.net/radio/abdullah_almousa",
  ),
  RadioStation(
    id: 121,
    englishName: "Abdullah Al-Khalaf",
    arabicName: "إذاعة عبدالله الخلف",
    url: "https://backup.qurango.net/radio/abdullah_alkhalaf",
  ),
  RadioStation(
    id: 122,
    englishName: "---Amazing short Recitations---",
    arabicName: "-تراتيل قصيرة متميزة-",
    url: "https://backup.qurango.net/radio/tarateel",
  ),
  RadioStation(
    id: 123,
    englishName: "Radio Majed Al-Zamil",
    arabicName: "إذاعة ماجد الزامل",
    url: "https://backup.qurango.net/radio/majed_alzamel",
  ),
  RadioStation(
    id: 124,
    englishName: "Radio Bandar Balilah",
    arabicName: "إذاعة بندر بليلة",
    url: "https://backup.qurango.net/radio/bandar_balilah",
  ),
  RadioStation(
    id: 125,
    englishName: "Radio Nasser Alosfor",
    arabicName: "إذاعة ناصر العصفور",
    url: "https://backup.qurango.net/radio/nasser_alosfor",
  ),
  RadioStation(
    id: 126,
    englishName: "Radio Muhammad Ayoub - Distinctive reading",
    arabicName: "إذاعة محمد أيوب - قراءة مميزة-",
    url: "https://backup.qurango.net/radio/ayyoub2",
  ),
  RadioStation(
    id: 127,
    englishName: "Ahmad Deban",
    arabicName: "إذاعة أحمد ديبان",
    url: "https://backup.qurango.net/radio/ahmad_deban",
  ),
  RadioStation(
    id: 128,
    englishName: "Radio Muhammad Abu Sneina",
    arabicName: "أذاعة محمد أبوسنينة",
    url: "https://backup.qurango.net/radio/sneineh",
  ),
  RadioStation(
    id: 129,
    englishName: "Radio Mohammed Al-Amin Qeniwa",
    arabicName: "إذاعة محمد الأمين قنيوة",
    url: "https://backup.qurango.net/radio/qeniwa",
  ),
  RadioStation(
    id: 130,
    englishName: "Radio Abdulrahman Alshahhat",
    arabicName: "إذاعة عبدالرحمن الشحات",
    url: "https://backup.qurango.net/radio/a_alshahhat",
  ),
  RadioStation(
    id: 131,
    englishName: "Abdulaziz Sheim",
    arabicName: "عبدالعزيز سحيم",
    url: "https://backup.qurango.net/radio/a_sheim",
  ),
  RadioStation(
    id: 132,
    englishName: "Verses of serenity",
    arabicName: "آيات السكينة",
    url: "https://backup.qurango.net/radio/sakeenah",
  ),
  RadioStation(
    id: 133,
    englishName:
        "Stories from the lives of the SAHABAH and TABE'EEN, may ALLAH be pleased with them",
    arabicName: "---إذاعة صور من حياة الصحابة والتابعين رضوان الله عليهم---",
    url: "https://backup.qurango.net/radio/sahabah",
  ),
  RadioStation(
    id: 134,
    englishName: "A summary of the interpretation of the Holy Quran",
    arabicName: "المختصر في تفسير القرآن الكريم",
    url: "https://backup.qurango.net/radio/mukhtasartafsir",
  ),
  RadioStation(
    id: 135,
    englishName: "Words of remembrance for morning",
    arabicName: "أذكار الصباح",
    url: "https://backup.qurango.net/radio/athkar_sabah",
  ),
  RadioStation(
    id: 136,
    englishName: "Words of remembrance for evening",
    arabicName: "أذكار المساء",
    url: "https://backup.qurango.net/radio/athkar_masa",
  ),
  RadioStation(
    id: 137,
    englishName: "In the shadows of the Prophet's PBUH biography",
    arabicName:
        "في ظلال السيرة النبوية - 400 حلقة عن سيرة نبينا محمد صلى الله عليه وسلم",
    url: "https://backup.qurango.net/radio/fi_zilal_alsiyra",
  ),
  RadioStation(
    id: 138,
    englishName: "The Abridged Biography of the Prophet",
    arabicName: "المختصر في السيرة النبوية",
    url: "https://backup.qurango.net/radio/almukhtasar_fi_alsiyra",
  ),
  RadioStation(
    id: 139,
    englishName:
        "The book of jurisprudential choices in matters of worship and transactions",
    arabicName: "كتاب الاختيارات الفقهية في مسائل العبادات والمعاملات",
    url: "https://backup.qurango.net/radio/alaikhtiarat_alfiqhayh_bin_baz",
  ),
  RadioStation(
    id: 140,
    englishName:
        "Interpretation of the Holy Qur'an - Conclusion from Tafsir al-Tabari",
    arabicName: "تفسير القران الكريم-الخلاصة من تفسير الطبري",
    url: "https://backup.qurango.net/radio/tabri",
  ),
  RadioStation(
    id: 141,
    englishName: "Saleh Al-Habdan",
    arabicName: "صالح الهبدان",
    url: "https://backup.qurango.net/radio/saleh_alhabdan",
  ),
  RadioStation(
    id: 142,
    englishName: "Al-Mulk Surah",
    arabicName: "سورة الملك",
    url: "https://backup.qurango.net/radio/Surah_Al-Mulk",
  ),
  RadioStation(
    id: 143,
    englishName: "The virtue of the month of Ramadan",
    arabicName: "فضل شهر رمضان",
    url: "https://backup.qurango.net/radio/ramadan",
  ),
  RadioStation(
    id: 144,
    englishName: "Sahih Muslim",
    arabicName: "صحيح مسلم",
    url: "https://backup.qurango.net/radio/saheh-muslim",
  ),
  RadioStation(
    id: 145,
    englishName: "Sahih al-Bukhari",
    arabicName: "صحيح البخاري",
    url: "https://backup.qurango.net/radio/saheh-bokharee",
  ),
  RadioStation(
    id: 146,
    englishName: "Stories of the Prophets",
    arabicName: "***قصص الأنبياء***",
    url: "https://backup.qurango.net/radio/alanbiya",
  ),
  RadioStation(
    id: 147,
    englishName: "Riyad Al-Salihin",
    arabicName: "رياض الصالحين",
    url: "https://backup.qurango.net/radio/riyad",
  ),
  RadioStation(
    id: 148,
    englishName: "Abdullah Albuajan",
    arabicName: "عبدالله البعيجان",
    url: "https://backup.qurango.net/radio/buajan",
  ),
  RadioStation(
    id: 149,
    englishName: "Ahmad Talib bin Humaid",
    arabicName: "أحمد طالب بن حميد",
    url: "https://backup.qurango.net/radio/a_binhameed",
  ),
  RadioStation(
    id: 150,
    englishName: "Tafsir Gharib Al-Quran",
    arabicName: "تفسير غريب القرآن",
    url: "https://backup.qurango.net/radio/gareeb-quran",
  ),
  RadioStation(
    id: 151,
    englishName: "Bader Alturki",
    arabicName: "بدر التركي",
    url: "https://backup.qurango.net/radio/bader",
  ),
  RadioStation(
    id: 152,
    englishName: "Hazza Al-Balushi",
    arabicName: "هزاع البلوشي",
    url: "https://backup.qurango.net/radio/hazza",
  ),
  RadioStation(
    id: 153,
    englishName: "Holy Quran from Saudia Arabia",
    arabicName: "إذاعة القرآن الكريم - السعودية",
    url: "https://stream.radiojar.com/0tpy1h0kxtzuv",
  ),
  RadioStation(
    id: 154,
    englishName: "Al-Shama'il Al-Muhammadiyyah",
    arabicName: "الشمائل المحمدية",
    url: "https://backup.qurango.net/radio/shmaeel",
  ),
  RadioStation(
    id: 155,
    englishName: "Holy Quran Radio from Cairo",
    arabicName: "إذاعة القرآن الكريم من القاهرة",
    url:
        "https://stream.radiojar.com/8s5u5tpdtwzuv",
        // "https://n0e.radiojar.com/8s5u5tpdtwzuv?rj-ttl=5&rj-tok=AAABjW7yROAA0TUU8cXhXIAi6g",
  ),
];
